openapi: 3.0.0
info:
  title: DocStrongBox API
  version: 1.0.0
  description: API for managing file uploads, downloads, updates, and deletions with sensitivity handling and user access rights.

servers:
  - url: http://localhost:3000/
    description: DocStrongBox API server

tags:
  - name: DocStrongBox
    description: Routes for managing document storage and access
  - name: Documentation
    description: Routes for accessing API documentation

paths:
###################################
#       DocStrongBox Routes       #
###################################
  /:
    post:
      tags:
        - DocStrongBox
      summary: Upload a file
      description: Upload a file with specified sensitivity and group access.
      operationId: uploadFile
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                AccessToken:
                  type: string
                  description: JWT AccessToken for user authentication.
                groupId:
                  type: string
                  description: ID of the group that will have access to the file.
                sensitivity:
                  type: string
                  enum: [low, medium, high]
                  description: Sensitivity level of the file.
                file:
                  type: string
                  format: binary
                  description: The file to upload.
      responses:
        '201':
          description: File successfully uploaded.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: File correctly uploaded
                  fileId:
                    type: string
                    description: ID of the uploaded file.
        '400':
          description: Bad Request due to missing parameters.
        '401':
          description: Unauthorized due to authentication failure.
        '404':
          description: Not Found if group or file does not exist.
        '500':
          description: Internal Server Error.

    get:
      tags:
        - DocStrongBox
      summary: Download a file
      description: Download a specified file if the user has the right access.
      operationId: downloadFile
      parameters:
        - in: query
          name: fileId
          required: true
          schema:
            type: string
          description: ID of the file to download.
        - in: query
          name: AccessToken
          required: true
          schema:
            type: string
          description: JWT AccessToken for user authentication.
      responses:
        '200':
          description: File successfully downloaded.
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
        '400':
          description: Bad Request due to missing parameters.
        '401':
          description: Unauthorized due to authentication failure or insufficient rights.
        '404':
          description: Not Found if the file does not exist.
        '500':
          description: Internal Server Error.

    put:
      tags:
        - DocStrongBox
      summary: Update a file
      description: Update an existing file with new data and sensitivity level.
      operationId: updateFile
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                AccessToken:
                  type: string
                  description: JWT AccessToken for user authentication.
                fileId:
                  type: string
                  description: ID of the file to update.
                sensitivity:
                  type: string
                  enum: [low, medium, high]
                  description: New sensitivity level of the file.
                file:
                  type: string
                  format: binary
                  description: The new file to upload.
      responses:
        '201':
          description: File successfully updated.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: File correctly updated
        '400':
          description: Bad Request due to missing parameters.
        '401':
          description: Unauthorized due to authentication failure or insufficient rights.
        '404':
          description: Not Found if the file does not exist.
        '500':
          description: Internal Server Error.

    delete:
      tags:
        - DocStrongBox
      summary: Delete a file
      description: Delete a specified file if the user has the right access.
      operationId: deleteFile
      parameters:
        - in: query
          name: fileId
          required: true
          schema:
            type: string
          description: ID of the file to delete.
        - in: query
          name: AccessToken
          required: true
          schema:
            type: string
          description: JWT AccessToken for user authentication.
      responses:
        '204':
          description: File successfully deleted.
        '400':
          description: Bad Request due to missing parameters.
        '401':
          description: Unauthorized due to authentication failure or insufficient rights.
        '404':
          description: Not Found if the file does not exist.
        '500':
          description: Internal Server Error.
  
  /files:
    get:
      tags:
          - DocStrongBox
      summary: Retrieve files accessible to the authenticated user
      description: Fetch a list of files that the authenticated user has rights to access.
      operationId: getFiles
      parameters:
        - in: query
          name: AccessToken
          required: true
          schema:
            type: string
          description: JWT AccessToken for user authentication.
      responses:
        '200':
          description: List of accessible files retrieved successfully.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    _id:
                      type: string
                      description: Unique identifier of the file.
                      example: "5f8f8c44b54764421b7164a2"
                    originalName:
                      type: string
                      description: Original name of the file.
                      example: "example.txt"
        '400':
          description: Bad Request due to missing AccessToken.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Missing AccessToken
        '501':
          description: Internal Server Error due to issues with authentication, rights retrieval, or file access.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Internal error while getting rights"
      
  /api-doc:
    get:
      tags:
        - Documentation
      summary: Get API documentation
      description: Returns the Swagger API documentation for the DocStrongBox API.
      operationId: getApiDoc
      responses:
        '200':
          description: Swagger documentation successfully retrieved.
          content:
            application/json:
              schema:
                type: object
                properties:
                  swagger:
                    type: string
                    example: "2.0"
                  info:
                    type: object
                    properties:
                      title:
                        type: string
                        example: "DocStrongBox API"
                      version:
                        type: string
                        example: "1.0.0"
                      description:
                        type: string
                        example: "API for managing file uploads, downloads, updates, and deletions with sensitivity handling and user access rights."
        '500':
          description: Internal Server Error.
